# Generated by Django 3.1.7 on 2021-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_delete_ownedgameitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedgames',
            name='games',
        ),
        migrations.AddField(
            model_name='ownedgames',
            name='games',
            field=models.ManyToManyField(to='games.Game'),
        ),
    ]
