# Generated by Django 3.1.7 on 2021-02-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_auto_20210227_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='games',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='basket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket_item', to='basket.basket'),
        ),
    ]
