# Generated by Django 3.1.7 on 2021-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_delete_ownedgameitem'),
        ('basket', '0003_auto_20210227_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='games',
            field=models.ManyToManyField(through='basket.BasketItem', to='games.Game'),
        ),
    ]
